"""empty message

Revision ID: fce8ff4e06f9
Revises: 
Create Date: 2024-06-07 01:41:55.876190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce8ff4e06f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('music', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_table')
    # ### end Alembic commands ###
